#!/bin/bash
# WORKER — picks up queued tasks and executes them with cheap models
# Each task runs in a git worktree, creates a PR when done
set -euo pipefail

PROJECT_DIR="$HOME/voice-journal"
QUEUE_DIR="$PROJECT_DIR/scripts/agents/queue"
LOG_DIR="$PROJECT_DIR/scripts/agents/logs"
DONE_DIR="$PROJECT_DIR/scripts/agents/done"

mkdir -p "$QUEUE_DIR" "$LOG_DIR" "$DONE_DIR"

# Find pending task files
TASKS=$(find "$QUEUE_DIR" -name "task_*.json" -type f 2>/dev/null | sort)

if [ -z "$TASKS" ]; then
    echo "No tasks in queue."
    exit 0
fi

for TASK_FILE in $TASKS; do
    TASK_ID=$(python3 -c "import json; print(json.load(open('$TASK_FILE'))['id'])")
    TASK_TYPE=$(python3 -c "import json; print(json.load(open('$TASK_FILE')).get('type','code'))")
    MODEL=$(python3 -c "import json; print(json.load(open('$TASK_FILE')).get('model','haiku'))")
    TITLE=$(python3 -c "import json; print(json.load(open('$TASK_FILE'))['title'])")
    DESC=$(python3 -c "import json; print(json.load(open('$TASK_FILE'))['description'])")
    BRANCH="auto/${TASK_ID}"

    echo "═══════════════════════════════════════"
    echo "Working: $TITLE"
    echo "Model: $MODEL | Type: $TASK_TYPE"
    echo "═══════════════════════════════════════"

    if [ "$TASK_TYPE" = "content" ]; then
        # ─── CONTENT TASKS (social media, copy) ───
        # Output goes to a content drafts folder, no code changes
        CONTENT_DIR="$PROJECT_DIR/scripts/agents/content"
        mkdir -p "$CONTENT_DIR"

        claude --model "$MODEL" -p "$(cat <<PROMPT
You are a content creator for Voice Journal — a voice-first journaling app.

Task: $TITLE
Details: $DESC

Write the content and save it. For Twitter/X threads, format as numbered tweets.
For blog posts, use markdown. For social captions, keep them punchy.

Include relevant hashtags and hooks.
PROMPT
)" --allowedTools "Write,Read" \
          --output-format json 2>/dev/null | jq -r '.result' > "$CONTENT_DIR/${TASK_ID}.md"

        echo "Content saved to: $CONTENT_DIR/${TASK_ID}.md"

    else
        # ─── CODE/TEST TASKS — work in a branch, create PR ───
        cd "$PROJECT_DIR"

        # Create branch
        git checkout -b "$BRANCH" main 2>/dev/null || git checkout "$BRANCH"

        claude --model "$MODEL" -p "$(cat <<PROMPT
You are a developer working on Voice Journal (~/voice-journal/).
Read ~/voice-journal/CLAUDE.md for project context.

YOUR TASK:
$TITLE

DETAILS:
$DESC

RULES:
- Make focused, minimal changes — only what the task requires
- Don't refactor unrelated code
- Test your changes compile: run 'npx next build' for frontend, 'uv run python -c "from app.main import app"' for backend
- Stage and commit your changes with a clear message
PROMPT
)" --allowedTools "Read,Edit,Write,Glob,Grep,Bash(git add *),Bash(git commit *),Bash(npm *),Bash(npx *),Bash(uv run *),Bash(cd *),Bash(ls *),Bash(mkdir *)"

        # Push and create PR
        git push -u origin "$BRANCH" 2>/dev/null && \
        gh pr create \
            --title "$TITLE" \
            --body "$(cat <<EOF
## Auto-generated by Voice Journal Agent Pipeline

**Task:** $TITLE
**Model:** $MODEL
**Type:** $TASK_TYPE

### Description
$DESC

---
Review and merge if it looks good.
EOF
)" --base main 2>/dev/null || echo "PR may already exist"

        # Back to main
        git checkout main 2>/dev/null
    fi

    # Move task to done
    mv "$TASK_FILE" "$DONE_DIR/"
    echo "[$(date)] Completed: $TASK_ID" >> "$LOG_DIR/worker.log"
    echo "Done: $TITLE"
    echo ""
done

echo "All tasks processed."
